// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package database

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const countApiKeys = `-- name: CountApiKeys :one
select count(*) as total from api_keys
`

func (q *Queries) CountApiKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countApiKeys)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createApiKey = `-- name: CreateApiKey :one
insert into api_keys (
  name, prefix, secret_hash, scopes, environments, platforms, role,
  is_bootstrap, expires_at, created_by, updated_by
) values (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $10
)
returning id, name, prefix, scopes, environments, platforms, role,
          is_bootstrap, expires_at, revoked_at, last_used_at, created_at, created_by
`

type CreateApiKeyParams struct {
	Name         string     `db:"name" json:"name"`
	Prefix       string     `db:"prefix" json:"prefix"`
	SecretHash   []byte     `db:"secret_hash" json:"secret_hash"`
	Scopes       []string   `db:"scopes" json:"scopes"`
	Environments []string   `db:"environments" json:"environments"`
	Platforms    []string   `db:"platforms" json:"platforms"`
	Role         string     `db:"role" json:"role"`
	IsBootstrap  bool       `db:"is_bootstrap" json:"is_bootstrap"`
	ExpiresAt    *time.Time `db:"expires_at" json:"expires_at"`
	Actor        string     `db:"actor" json:"actor"`
}

type CreateApiKeyRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	Prefix       string     `db:"prefix" json:"prefix"`
	Scopes       []string   `db:"scopes" json:"scopes"`
	Environments []string   `db:"environments" json:"environments"`
	Platforms    []string   `db:"platforms" json:"platforms"`
	Role         string     `db:"role" json:"role"`
	IsBootstrap  bool       `db:"is_bootstrap" json:"is_bootstrap"`
	ExpiresAt    *time.Time `db:"expires_at" json:"expires_at"`
	RevokedAt    *time.Time `db:"revoked_at" json:"revoked_at"`
	LastUsedAt   *time.Time `db:"last_used_at" json:"last_used_at"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	CreatedBy    string     `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (CreateApiKeyRow, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.Name,
		arg.Prefix,
		arg.SecretHash,
		arg.Scopes,
		arg.Environments,
		arg.Platforms,
		arg.Role,
		arg.IsBootstrap,
		arg.ExpiresAt,
		arg.Actor,
	)
	var i CreateApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.Scopes,
		&i.Environments,
		&i.Platforms,
		&i.Role,
		&i.IsBootstrap,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getApiKeyForAuth = `-- name: GetApiKeyForAuth :one
select k.id, k.name, k.prefix, k.secret_hash, k.scopes, k.environments,
       k.platforms, k.role, k.is_bootstrap, k.expires_at, k.revoked_at,
       r.rank as role_rank
  from api_keys k
  join roles r on r.name = k.role
 where k.prefix = $1
`

type GetApiKeyForAuthRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	Prefix       string     `db:"prefix" json:"prefix"`
	SecretHash   []byte     `db:"secret_hash" json:"secret_hash"`
	Scopes       []string   `db:"scopes" json:"scopes"`
	Environments []string   `db:"environments" json:"environments"`
	Platforms    []string   `db:"platforms" json:"platforms"`
	Role         string     `db:"role" json:"role"`
	IsBootstrap  bool       `db:"is_bootstrap" json:"is_bootstrap"`
	ExpiresAt    *time.Time `db:"expires_at" json:"expires_at"`
	RevokedAt    *time.Time `db:"revoked_at" json:"revoked_at"`
	RoleRank     int32      `db:"role_rank" json:"role_rank"`
}

// The hot path: one indexed read on the public prefix. The caller then
// compares the secret hash in constant time. The role's rank comes along so
// authorisation needs no second round trip.
func (q *Queries) GetApiKeyForAuth(ctx context.Context, prefix string) (GetApiKeyForAuthRow, error) {
	row := q.db.QueryRow(ctx, getApiKeyForAuth, prefix)
	var i GetApiKeyForAuthRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scopes,
		&i.Environments,
		&i.Platforms,
		&i.Role,
		&i.IsBootstrap,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RoleRank,
	)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
select id, name, prefix, scopes, environments, platforms, role, is_bootstrap,
       expires_at, revoked_at, last_used_at, created_at, created_by
  from api_keys
 where $1::bool or revoked_at is null
 order by created_at desc
`

type ListApiKeysRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	Prefix       string     `db:"prefix" json:"prefix"`
	Scopes       []string   `db:"scopes" json:"scopes"`
	Environments []string   `db:"environments" json:"environments"`
	Platforms    []string   `db:"platforms" json:"platforms"`
	Role         string     `db:"role" json:"role"`
	IsBootstrap  bool       `db:"is_bootstrap" json:"is_bootstrap"`
	ExpiresAt    *time.Time `db:"expires_at" json:"expires_at"`
	RevokedAt    *time.Time `db:"revoked_at" json:"revoked_at"`
	LastUsedAt   *time.Time `db:"last_used_at" json:"last_used_at"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	CreatedBy    string     `db:"created_by" json:"created_by"`
}

// Never selects secret_hash: nothing outside authentication needs it.
func (q *Queries) ListApiKeys(ctx context.Context, includeRevoked bool) ([]ListApiKeysRow, error) {
	rows, err := q.db.Query(ctx, listApiKeys, includeRevoked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApiKeysRow{}
	for rows.Next() {
		var i ListApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Scopes,
			&i.Environments,
			&i.Platforms,
			&i.Role,
			&i.IsBootstrap,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :execrows
update api_keys
   set revoked_at = now(), updated_by = $1
 where id = $2 and revoked_at is null
`

type RevokeApiKeyParams struct {
	Actor string    `db:"actor" json:"actor"`
	ID    uuid.UUID `db:"id" json:"id"`
}

// Revocation is permanent and never removes the row, so an audit of which key
// did what survives.
func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeApiKey, arg.Actor, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchApiKey = `-- name: TouchApiKey :exec
update api_keys
   set last_used_at = now()
 where id = $1
   and (last_used_at is null
        or last_used_at < now() - make_interval(secs => $2::int))
`

type TouchApiKeyParams struct {
	ID              uuid.UUID `db:"id" json:"id"`
	ThrottleSeconds int32     `db:"throttle_seconds" json:"throttle_seconds"`
}

// Records use at most once per throttle window, keeping authentication from
// turning every read into a write.
func (q *Queries) TouchApiKey(ctx context.Context, arg TouchApiKeyParams) error {
	_, err := q.db.Exec(ctx, touchApiKey, arg.ID, arg.ThrottleSeconds)
	return err
}
