// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package database

import (
	"context"

	uuid "github.com/google/uuid"
)

const addGroupMembers = `-- name: AddGroupMembers :exec
insert into group_members (group_id, user_id, created_by)
select $1, unnest($2::text[]), $3
on conflict (group_id, user_id) do nothing
`

type AddGroupMembersParams struct {
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
	UserIds []string  `db:"user_ids" json:"user_ids"`
	Actor   string    `db:"actor" json:"actor"`
}

// Adds every user in one round trip; re-adding an existing member is a no-op.
func (q *Queries) AddGroupMembers(ctx context.Context, arg AddGroupMembersParams) error {
	_, err := q.db.Exec(ctx, addGroupMembers, arg.GroupID, arg.UserIds, arg.Actor)
	return err
}

const createGroup = `-- name: CreateGroup :one
insert into groups (name, description, environment, priority, is_ephemeral, created_by, updated_by)
values ($1, $2, $3, $4, $5, $6, $6)
returning id, name, description, environment, priority, is_ephemeral, created_at, created_by, updated_at, updated_by
`

type CreateGroupParams struct {
	Name        string  `db:"name" json:"name"`
	Description string  `db:"description" json:"description"`
	Environment *string `db:"environment" json:"environment"`
	Priority    int32   `db:"priority" json:"priority"`
	IsEphemeral bool    `db:"is_ephemeral" json:"is_ephemeral"`
	Actor       string  `db:"actor" json:"actor"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Description,
		arg.Environment,
		arg.Priority,
		arg.IsEphemeral,
		arg.Actor,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Environment,
		&i.Priority,
		&i.IsEphemeral,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
delete from groups where id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGroup = `-- name: GetGroup :one
select id, name, description, environment, priority, is_ephemeral, created_at, created_by, updated_at, updated_by from groups where id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Environment,
		&i.Priority,
		&i.IsEphemeral,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
select group_id, user_id, created_at, created_by from group_members where group_id = $1 order by user_id
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMember{}
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
select id, name, description, environment, priority, is_ephemeral, created_at, created_by, updated_at, updated_by from groups
 where ($1::text = '' or environment = $1 or environment is null)
   and ($2::bool or not is_ephemeral)
 order by priority desc, name
`

type ListGroupsParams struct {
	Environment      string `db:"environment" json:"environment"`
	IncludeEphemeral bool   `db:"include_ephemeral" json:"include_ephemeral"`
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups, arg.Environment, arg.IncludeEphemeral)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Environment,
			&i.Priority,
			&i.IsEphemeral,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
select g.id, g.name, g.description, g.environment, g.priority, g.is_ephemeral, g.created_at, g.created_by, g.updated_at, g.updated_by from groups g
  join group_members m on m.group_id = g.id
 where m.user_id = $1
 order by g.priority desc, g.created_at
`

func (q *Queries) ListGroupsForUser(ctx context.Context, userID string) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Environment,
			&i.Priority,
			&i.IsEphemeral,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMembers = `-- name: RemoveGroupMembers :execrows
delete from group_members
 where group_id = $1 and user_id = any($2::text[])
`

type RemoveGroupMembersParams struct {
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
	UserIds []string  `db:"user_ids" json:"user_ids"`
}

func (q *Queries) RemoveGroupMembers(ctx context.Context, arg RemoveGroupMembersParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGroupMembers, arg.GroupID, arg.UserIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGroup = `-- name: UpdateGroup :one
update groups
   set description = $1,
       priority    = $2,
       updated_by  = $3
 where id = $4
returning id, name, description, environment, priority, is_ephemeral, created_at, created_by, updated_at, updated_by
`

type UpdateGroupParams struct {
	Description string    `db:"description" json:"description"`
	Priority    int32     `db:"priority" json:"priority"`
	Actor       string    `db:"actor" json:"actor"`
	ID          uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.Description,
		arg.Priority,
		arg.Actor,
		arg.ID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Environment,
		&i.Priority,
		&i.IsEphemeral,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
