// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	uuid "github.com/google/uuid"
)

// Highest layer allowed to hold a value. PERSONAL permits server+group+user layers, INTERMEDIATE permits server+group, SERVER permits server only.
type SettingScope string

const (
	SettingScopePERSONAL     SettingScope = "PERSONAL"
	SettingScopeINTERMEDIATE SettingScope = "INTERMEDIATE"
	SettingScopeSERVER       SettingScope = "SERVER"
)

func (e *SettingScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SettingScope(s)
	case string:
		*e = SettingScope(s)
	default:
		return fmt.Errorf("unsupported scan type for SettingScope: %T", src)
	}
	return nil
}

type NullSettingScope struct {
	SettingScope SettingScope `json:"setting_scope"`
	Valid        bool         `json:"valid"` // Valid is true if SettingScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSettingScope) Scan(value interface{}) error {
	if value == nil {
		ns.SettingScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SettingScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSettingScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SettingScope), nil
}

type SettingType string

const (
	SettingTypeBOOLEAN  SettingType = "BOOLEAN"
	SettingTypeNUMBER   SettingType = "NUMBER"
	SettingTypeSTRING   SettingType = "STRING"
	SettingTypeDATETIME SettingType = "DATETIME"
	SettingTypeSELECT   SettingType = "SELECT"
	SettingTypeJSON     SettingType = "JSON"
)

func (e *SettingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SettingType(s)
	case string:
		*e = SettingType(s)
	default:
		return fmt.Errorf("unsupported scan type for SettingType: %T", src)
	}
	return nil
}

type NullSettingType struct {
	SettingType SettingType `json:"setting_type"`
	Valid       bool        `json:"valid"` // Valid is true if SettingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSettingType) Scan(value interface{}) error {
	if value == nil {
		ns.SettingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SettingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSettingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SettingType), nil
}

type ApiKey struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Name         string     `db:"name" json:"name"`
	Prefix       string     `db:"prefix" json:"prefix"`
	SecretHash   []byte     `db:"secret_hash" json:"secret_hash"`
	Scopes       []string   `db:"scopes" json:"scopes"`
	Environments []string   `db:"environments" json:"environments"`
	Platforms    []string   `db:"platforms" json:"platforms"`
	Role         string     `db:"role" json:"role"`
	IsBootstrap  bool       `db:"is_bootstrap" json:"is_bootstrap"`
	ExpiresAt    *time.Time `db:"expires_at" json:"expires_at"`
	RevokedAt    *time.Time `db:"revoked_at" json:"revoked_at"`
	LastUsedAt   *time.Time `db:"last_used_at" json:"last_used_at"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	CreatedBy    string     `db:"created_by" json:"created_by"`
	UpdatedAt    time.Time  `db:"updated_at" json:"updated_at"`
	UpdatedBy    string     `db:"updated_by" json:"updated_by"`
}

type Environment struct {
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	IsSystem    bool      `db:"is_system" json:"is_system"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type Group struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	Environment *string   `db:"environment" json:"environment"`
	Priority    int32     `db:"priority" json:"priority"`
	IsEphemeral bool      `db:"is_ephemeral" json:"is_ephemeral"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	CreatedBy   string    `db:"created_by" json:"created_by"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
	UpdatedBy   string    `db:"updated_by" json:"updated_by"`
}

type GroupMember struct {
	GroupID   uuid.UUID `db:"group_id" json:"group_id"`
	UserID    string    `db:"user_id" json:"user_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	CreatedBy string    `db:"created_by" json:"created_by"`
}

type IntermediateSetting struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	GroupID    uuid.UUID       `db:"group_id" json:"group_id"`
	SettingID  uuid.UUID       `db:"setting_id" json:"setting_id"`
	Value      json.RawMessage `db:"value" json:"value"`
	Visible    bool            `db:"visible" json:"visible"`
	IsEnforced bool            `db:"is_enforced" json:"is_enforced"`
	CreatedAt  time.Time       `db:"created_at" json:"created_at"`
	CreatedBy  string          `db:"created_by" json:"created_by"`
	UpdatedAt  time.Time       `db:"updated_at" json:"updated_at"`
	UpdatedBy  string          `db:"updated_by" json:"updated_by"`
}

type PersonalSetting struct {
	ID        uuid.UUID       `db:"id" json:"id"`
	UserID    string          `db:"user_id" json:"user_id"`
	SettingID uuid.UUID       `db:"setting_id" json:"setting_id"`
	Value     json.RawMessage `db:"value" json:"value"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
	CreatedBy string          `db:"created_by" json:"created_by"`
	UpdatedAt time.Time       `db:"updated_at" json:"updated_at"`
	UpdatedBy string          `db:"updated_by" json:"updated_by"`
}

type Platform struct {
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	IsSystem    bool      `db:"is_system" json:"is_system"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type Role struct {
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	Rank        int32     `db:"rank" json:"rank"`
	IsSystem    bool      `db:"is_system" json:"is_system"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type ServerSetting struct {
	ID        uuid.UUID       `db:"id" json:"id"`
	SettingID uuid.UUID       `db:"setting_id" json:"setting_id"`
	Value     json.RawMessage `db:"value" json:"value"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
	CreatedBy string          `db:"created_by" json:"created_by"`
	UpdatedAt time.Time       `db:"updated_at" json:"updated_at"`
	UpdatedBy string          `db:"updated_by" json:"updated_by"`
}

type Setting struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	Name         string          `db:"name" json:"name"`
	Description  string          `db:"description" json:"description"`
	Type         SettingType     `db:"type" json:"type"`
	TypeConfig   json.RawMessage `db:"type_config" json:"type_config"`
	Role         string          `db:"role" json:"role"`
	Scope        SettingScope    `db:"scope" json:"scope"`
	Platform     string          `db:"platform" json:"platform"`
	Environment  string          `db:"environment" json:"environment"`
	DefaultValue json.RawMessage `db:"default_value" json:"default_value"`
	CreatedAt    time.Time       `db:"created_at" json:"created_at"`
	CreatedBy    string          `db:"created_by" json:"created_by"`
	UpdatedAt    time.Time       `db:"updated_at" json:"updated_at"`
	UpdatedBy    string          `db:"updated_by" json:"updated_by"`
}
