// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	// Adds every user in one round trip; re-adding an existing member is a no-op.
	AddGroupMembers(ctx context.Context, arg AddGroupMembersParams) error
	CountApiKeys(ctx context.Context) (int64, error)
	// How many values would be destroyed along with this setting.
	CountSettingValues(ctx context.Context, settingID uuid.UUID) (int32, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (CreateApiKeyRow, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateSetting(ctx context.Context, arg CreateSettingParams) (Setting, error)
	DeleteEnvironment(ctx context.Context, name string) (int64, error)
	DeleteGroup(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteIntermediateValue(ctx context.Context, arg DeleteIntermediateValueParams) (int64, error)
	DeletePersonalValue(ctx context.Context, arg DeletePersonalValueParams) (int64, error)
	DeletePlatform(ctx context.Context, name string) (int64, error)
	// Refuses to remove a system row; :execrows lets the caller tell "protected"
	// from "absent" by checking whether the row still exists.
	DeleteRole(ctx context.Context, name string) (int64, error)
	DeleteServerValue(ctx context.Context, settingID uuid.UUID) (int64, error)
	DeleteSetting(ctx context.Context, id uuid.UUID) (int64, error)
	// The hot path: one indexed read on the public prefix. The caller then
	// compares the secret hash in constant time. The role's rank comes along so
	// authorisation needs no second round trip.
	GetApiKeyForAuth(ctx context.Context, prefix string) (GetApiKeyForAuthRow, error)
	GetEnvironment(ctx context.Context, name string) (Environment, error)
	GetGroup(ctx context.Context, id uuid.UUID) (Group, error)
	GetIntermediateValue(ctx context.Context, arg GetIntermediateValueParams) (IntermediateSetting, error)
	GetPersonalValue(ctx context.Context, arg GetPersonalValueParams) (PersonalSetting, error)
	GetPlatform(ctx context.Context, name string) (Platform, error)
	GetRole(ctx context.Context, name string) (Role, error)
	GetServerValue(ctx context.Context, settingID uuid.UUID) (ServerSetting, error)
	GetSetting(ctx context.Context, id uuid.UUID) (Setting, error)
	GetSettingByName(ctx context.Context, arg GetSettingByNameParams) (Setting, error)
	// Never selects secret_hash: nothing outside authentication needs it.
	ListApiKeys(ctx context.Context, includeRevoked bool) ([]ListApiKeysRow, error)
	ListEnvironments(ctx context.Context) ([]Environment, error)
	ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GroupMember, error)
	ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error)
	ListGroupsForUser(ctx context.Context, userID string) ([]Group, error)
	ListIntermediateValuesForGroup(ctx context.Context, groupID uuid.UUID) ([]IntermediateSetting, error)
	ListPersonalValuesForUser(ctx context.Context, userID string) ([]PersonalSetting, error)
	ListPlatforms(ctx context.Context) ([]Platform, error)
	// Roles, platforms and environments are all name-keyed lookup tables with the
	// same shape, so the queries below are deliberately parallel.
	ListRoles(ctx context.Context) ([]Role, error)
	// Filters are optional: pass an empty string or empty array to ignore one.
	ListSettings(ctx context.Context, arg ListSettingsParams) ([]Setting, error)
	RemoveGroupMembers(ctx context.Context, arg RemoveGroupMembersParams) (int64, error)
	// Every setting a user can see, already collapsed to one effective value.
	//
	// Precedence, lowest to highest:
	//   default_value < server < intermediate (advisory) < personal < intermediate (enforced)
	//
	// SERVER-scoped settings come back too: a client needs them to know which
	// features are switched on. The role filter is what keeps a `user` from
	// seeing settings declared for `staff` or `admin`.
	// Groups the user belongs to, plus any ad-hoc groups named by the caller.
	// One winning override per setting per direction. Highest group priority
	// wins; the older group breaks a tie so the result is stable.
	ResolveForUser(ctx context.Context, arg ResolveForUserParams) ([]ResolveForUserRow, error)
	// The server's own settings: no user, no groups, just the server layer over
	// the declared default.
	ResolveServer(ctx context.Context, arg ResolveServerParams) ([]ResolveServerRow, error)
	// Revocation is permanent and never removes the row, so an audit of which key
	// did what survives.
	RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (int64, error)
	// Records use at most once per throttle window, keeping authentication from
	// turning every read into a write.
	TouchApiKey(ctx context.Context, arg TouchApiKeyParams) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	// Only description, type_config, role and default_value may change. A
	// setting's type, scope and target are structural: changing them would
	// invalidate values already stored against it.
	UpdateSetting(ctx context.Context, arg UpdateSettingParams) (Setting, error)
	UpsertEnvironment(ctx context.Context, arg UpsertEnvironmentParams) (Environment, error)
	UpsertIntermediateValue(ctx context.Context, arg UpsertIntermediateValueParams) (IntermediateSetting, error)
	UpsertPersonalValue(ctx context.Context, arg UpsertPersonalValueParams) (PersonalSetting, error)
	UpsertPlatform(ctx context.Context, arg UpsertPlatformParams) (Platform, error)
	UpsertRole(ctx context.Context, arg UpsertRoleParams) (Role, error)
	// Each layer gets the same three operations. Writes are upserts so that a
	// caller can PUT a value without first checking whether one exists.
	UpsertServerValue(ctx context.Context, arg UpsertServerValueParams) (ServerSetting, error)
}

var _ Querier = (*Queries)(nil)
