// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resolve.sql

package database

import (
	"context"
	"encoding/json"

	uuid "github.com/google/uuid"
)

const resolveForUser = `-- name: ResolveForUser :many
with visible as (
  select s.id, s.name, s.description, s.type, s.type_config, s.role,
         s.scope, s.platform, s.environment, s.default_value
    from settings s
    join roles r on r.name = s.role
   where s.environment = $2
     and (cardinality($3::text[]) = 0 or s.platform = any($3::text[]))
     and r.rank <= $4::int
),
member_groups as (
  select g.id, g.priority, g.created_at
    from groups g
   where (g.environment is null or g.environment = $2)
     and (
       exists (select 1 from group_members m
                where m.group_id = g.id and m.user_id = $1)
       or g.id = any($5::uuid[])
     )
),
overrides as (
  select distinct on (i.setting_id, i.is_enforced)
         i.setting_id, i.value, i.visible, i.is_enforced, i.group_id
    from intermediate_settings i
    join member_groups mg on mg.id = i.group_id
   order by i.setting_id, i.is_enforced, mg.priority desc, mg.created_at
)
select
  s.id, s.name, s.description, s.type, s.type_config, s.role, s.scope,
  s.platform, s.environment,

  coalesce(enforced.value, personal.value, advisory.value, server.value, s.default_value) as value,

  case
    when enforced.value  is not null then 'INTERMEDIATE'
    when personal.value  is not null then 'PERSONAL'
    when advisory.value  is not null then 'INTERMEDIATE'
    when server.value    is not null then 'SERVER'
    when s.default_value is not null then 'DEFAULT'
    else 'UNSET'
  end as source,

  -- Both candidate overrides, left joined so an absent one is NULL. Which of
  -- them actually took effect depends on whether the user set a value, and
  -- that last step is clearer in Go than in a nest of CASE expressions.
  enforced.group_id as enforced_group_id,
  enforced.visible  as enforced_visible,
  advisory.group_id as advisory_group_id,
  advisory.visible  as advisory_visible,
  personal.value    as personal_value

from visible s
left join personal_settings personal
       on personal.setting_id = s.id and personal.user_id = $1
left join overrides enforced on enforced.setting_id = s.id and enforced.is_enforced
left join overrides advisory on advisory.setting_id = s.id and not advisory.is_enforced
left join server_settings server on server.setting_id = s.id
order by s.name
`

type ResolveForUserParams struct {
	UserID        string      `db:"user_id" json:"user_id"`
	Environment   string      `db:"environment" json:"environment"`
	Platforms     []string    `db:"platforms" json:"platforms"`
	MaxRank       int32       `db:"max_rank" json:"max_rank"`
	AdHocGroupIds []uuid.UUID `db:"ad_hoc_group_ids" json:"ad_hoc_group_ids"`
}

type ResolveForUserRow struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	Name            string          `db:"name" json:"name"`
	Description     string          `db:"description" json:"description"`
	Type            SettingType     `db:"type" json:"type"`
	TypeConfig      json.RawMessage `db:"type_config" json:"type_config"`
	Role            string          `db:"role" json:"role"`
	Scope           SettingScope    `db:"scope" json:"scope"`
	Platform        string          `db:"platform" json:"platform"`
	Environment     string          `db:"environment" json:"environment"`
	Value           json.RawMessage `db:"value" json:"value"`
	Source          string          `db:"source" json:"source"`
	EnforcedGroupID *uuid.UUID      `db:"enforced_group_id" json:"enforced_group_id"`
	EnforcedVisible *bool           `db:"enforced_visible" json:"enforced_visible"`
	AdvisoryGroupID *uuid.UUID      `db:"advisory_group_id" json:"advisory_group_id"`
	AdvisoryVisible *bool           `db:"advisory_visible" json:"advisory_visible"`
	PersonalValue   json.RawMessage `db:"personal_value" json:"personal_value"`
}

// Every setting a user can see, already collapsed to one effective value.
//
// Precedence, lowest to highest:
//
//	default_value < server < intermediate (advisory) < personal < intermediate (enforced)
//
// SERVER-scoped settings come back too: a client needs them to know which
// features are switched on. The role filter is what keeps a `user` from
// seeing settings declared for `staff` or `admin`.
// Groups the user belongs to, plus any ad-hoc groups named by the caller.
// One winning override per setting per direction. Highest group priority
// wins; the older group breaks a tie so the result is stable.
func (q *Queries) ResolveForUser(ctx context.Context, arg ResolveForUserParams) ([]ResolveForUserRow, error) {
	rows, err := q.db.Query(ctx, resolveForUser,
		arg.UserID,
		arg.Environment,
		arg.Platforms,
		arg.MaxRank,
		arg.AdHocGroupIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveForUserRow{}
	for rows.Next() {
		var i ResolveForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.TypeConfig,
			&i.Role,
			&i.Scope,
			&i.Platform,
			&i.Environment,
			&i.Value,
			&i.Source,
			&i.EnforcedGroupID,
			&i.EnforcedVisible,
			&i.AdvisoryGroupID,
			&i.AdvisoryVisible,
			&i.PersonalValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveServer = `-- name: ResolveServer :many
select
  s.id, s.name, s.description, s.type, s.type_config, s.role, s.scope,
  s.platform, s.environment,
  coalesce(v.value, s.default_value) as value,
  case
    when v.value         is not null then 'SERVER'
    when s.default_value is not null then 'DEFAULT'
    else 'UNSET'
  end as source
  from settings s
  join roles r on r.name = s.role
  left join server_settings v on v.setting_id = s.id
 where s.environment = $1
   and s.scope = 'SERVER'
   and (cardinality($2::text[]) = 0 or s.platform = any($2::text[]))
   and r.rank <= $3::int
 order by s.name
`

type ResolveServerParams struct {
	Environment string   `db:"environment" json:"environment"`
	Platforms   []string `db:"platforms" json:"platforms"`
	MaxRank     int32    `db:"max_rank" json:"max_rank"`
}

type ResolveServerRow struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	Name        string          `db:"name" json:"name"`
	Description string          `db:"description" json:"description"`
	Type        SettingType     `db:"type" json:"type"`
	TypeConfig  json.RawMessage `db:"type_config" json:"type_config"`
	Role        string          `db:"role" json:"role"`
	Scope       SettingScope    `db:"scope" json:"scope"`
	Platform    string          `db:"platform" json:"platform"`
	Environment string          `db:"environment" json:"environment"`
	Value       json.RawMessage `db:"value" json:"value"`
	Source      string          `db:"source" json:"source"`
}

// The server's own settings: no user, no groups, just the server layer over
// the declared default.
func (q *Queries) ResolveServer(ctx context.Context, arg ResolveServerParams) ([]ResolveServerRow, error) {
	rows, err := q.db.Query(ctx, resolveServer, arg.Environment, arg.Platforms, arg.MaxRank)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveServerRow{}
	for rows.Next() {
		var i ResolveServerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.TypeConfig,
			&i.Role,
			&i.Scope,
			&i.Platform,
			&i.Environment,
			&i.Value,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
