// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package database

import (
	"context"
	"encoding/json"

	uuid "github.com/google/uuid"
)

const countSettingValues = `-- name: CountSettingValues :one
select (select count(*) from personal_settings     p where p.setting_id = $1)
     + (select count(*) from intermediate_settings i where i.setting_id = $1)
     + (select count(*) from server_settings       v where v.setting_id = $1) as total
`

// How many values would be destroyed along with this setting.
func (q *Queries) CountSettingValues(ctx context.Context, settingID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countSettingValues, settingID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const createSetting = `-- name: CreateSetting :one
insert into settings (
  name, description, type, type_config, role, scope, platform, environment,
  default_value, created_by, updated_by
) values (
  $1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $10
)
returning id, name, description, type, type_config, role, scope, platform, environment, default_value, created_at, created_by, updated_at, updated_by
`

type CreateSettingParams struct {
	Name         string          `db:"name" json:"name"`
	Description  string          `db:"description" json:"description"`
	Type         SettingType     `db:"type" json:"type"`
	TypeConfig   json.RawMessage `db:"type_config" json:"type_config"`
	Role         string          `db:"role" json:"role"`
	Scope        SettingScope    `db:"scope" json:"scope"`
	Platform     string          `db:"platform" json:"platform"`
	Environment  string          `db:"environment" json:"environment"`
	DefaultValue json.RawMessage `db:"default_value" json:"default_value"`
	Actor        string          `db:"actor" json:"actor"`
}

func (q *Queries) CreateSetting(ctx context.Context, arg CreateSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, createSetting,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.TypeConfig,
		arg.Role,
		arg.Scope,
		arg.Platform,
		arg.Environment,
		arg.DefaultValue,
		arg.Actor,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.TypeConfig,
		&i.Role,
		&i.Scope,
		&i.Platform,
		&i.Environment,
		&i.DefaultValue,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteSetting = `-- name: DeleteSetting :execrows
delete from settings where id = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSetting, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSetting = `-- name: GetSetting :one
select id, name, description, type, type_config, role, scope, platform, environment, default_value, created_at, created_by, updated_at, updated_by from settings where id = $1
`

func (q *Queries) GetSetting(ctx context.Context, id uuid.UUID) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, id)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.TypeConfig,
		&i.Role,
		&i.Scope,
		&i.Platform,
		&i.Environment,
		&i.DefaultValue,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getSettingByName = `-- name: GetSettingByName :one
select id, name, description, type, type_config, role, scope, platform, environment, default_value, created_at, created_by, updated_at, updated_by from settings
 where name = $1 and platform = $2 and environment = $3
`

type GetSettingByNameParams struct {
	Name        string `db:"name" json:"name"`
	Platform    string `db:"platform" json:"platform"`
	Environment string `db:"environment" json:"environment"`
}

func (q *Queries) GetSettingByName(ctx context.Context, arg GetSettingByNameParams) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettingByName, arg.Name, arg.Platform, arg.Environment)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.TypeConfig,
		&i.Role,
		&i.Scope,
		&i.Platform,
		&i.Environment,
		&i.DefaultValue,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
select s.id, s.name, s.description, s.type, s.type_config, s.role, s.scope, s.platform, s.environment, s.default_value, s.created_at, s.created_by, s.updated_at, s.updated_by
  from settings s
  join roles r on r.name = s.role
 where ($1::text = '' or s.environment = $1)
   and ($2::text = '' or s.platform = $2)
   and ($3::text = '' or s.scope = $3::setting_scope)
   and r.rank <= $4::int
 order by s.environment, s.platform, s.name
`

type ListSettingsParams struct {
	Environment string `db:"environment" json:"environment"`
	Platform    string `db:"platform" json:"platform"`
	Scope       string `db:"scope" json:"scope"`
	MaxRank     int32  `db:"max_rank" json:"max_rank"`
}

// Filters are optional: pass an empty string or empty array to ignore one.
func (q *Queries) ListSettings(ctx context.Context, arg ListSettingsParams) ([]Setting, error) {
	rows, err := q.db.Query(ctx, listSettings,
		arg.Environment,
		arg.Platform,
		arg.Scope,
		arg.MaxRank,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.TypeConfig,
			&i.Role,
			&i.Scope,
			&i.Platform,
			&i.Environment,
			&i.DefaultValue,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSetting = `-- name: UpdateSetting :one
update settings
   set description   = $1,
       type_config   = $2,
       role          = $3,
       default_value = $4,
       updated_by    = $5
 where id = $6
returning id, name, description, type, type_config, role, scope, platform, environment, default_value, created_at, created_by, updated_at, updated_by
`

type UpdateSettingParams struct {
	Description  string          `db:"description" json:"description"`
	TypeConfig   json.RawMessage `db:"type_config" json:"type_config"`
	Role         string          `db:"role" json:"role"`
	DefaultValue json.RawMessage `db:"default_value" json:"default_value"`
	Actor        string          `db:"actor" json:"actor"`
	ID           uuid.UUID       `db:"id" json:"id"`
}

// Only description, type_config, role and default_value may change. A
// setting's type, scope and target are structural: changing them would
// invalidate values already stored against it.
func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSetting,
		arg.Description,
		arg.TypeConfig,
		arg.Role,
		arg.DefaultValue,
		arg.Actor,
		arg.ID,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.TypeConfig,
		&i.Role,
		&i.Scope,
		&i.Platform,
		&i.Environment,
		&i.DefaultValue,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
