// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taxonomy.sql

package database

import (
	"context"
)

const deleteEnvironment = `-- name: DeleteEnvironment :execrows
delete from environments where name = $1 and not is_system
`

func (q *Queries) DeleteEnvironment(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnvironment, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePlatform = `-- name: DeletePlatform :execrows
delete from platforms where name = $1 and not is_system
`

func (q *Queries) DeletePlatform(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlatform, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRole = `-- name: DeleteRole :execrows
delete from roles where name = $1 and not is_system
`

// Refuses to remove a system row; :execrows lets the caller tell "protected"
// from "absent" by checking whether the row still exists.
func (q *Queries) DeleteRole(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnvironment = `-- name: GetEnvironment :one
select name, description, is_system, created_at, updated_at from environments where name = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, name string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, name)
	var i Environment
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatform = `-- name: GetPlatform :one
select name, description, is_system, created_at, updated_at from platforms where name = $1
`

func (q *Queries) GetPlatform(ctx context.Context, name string) (Platform, error) {
	row := q.db.QueryRow(ctx, getPlatform, name)
	var i Platform
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
select name, description, rank, is_system, created_at, updated_at from roles where name = $1
`

func (q *Queries) GetRole(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, name)
	var i Role
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.Rank,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
select name, description, is_system, created_at, updated_at from environments order by name
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatforms = `-- name: ListPlatforms :many
select name, description, is_system, created_at, updated_at from platforms order by name
`

func (q *Queries) ListPlatforms(ctx context.Context) ([]Platform, error) {
	rows, err := q.db.Query(ctx, listPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Platform{}
	for rows.Next() {
		var i Platform
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many

select name, description, rank, is_system, created_at, updated_at from roles order by rank
`

// Roles, platforms and environments are all name-keyed lookup tables with the
// same shape, so the queries below are deliberately parallel.
func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Rank,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvironment = `-- name: UpsertEnvironment :one
insert into environments (name, description)
values ($1, $2)
on conflict (name) do update set description = excluded.description
returning name, description, is_system, created_at, updated_at
`

type UpsertEnvironmentParams struct {
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) UpsertEnvironment(ctx context.Context, arg UpsertEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, upsertEnvironment, arg.Name, arg.Description)
	var i Environment
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlatform = `-- name: UpsertPlatform :one
insert into platforms (name, description)
values ($1, $2)
on conflict (name) do update set description = excluded.description
returning name, description, is_system, created_at, updated_at
`

type UpsertPlatformParams struct {
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) UpsertPlatform(ctx context.Context, arg UpsertPlatformParams) (Platform, error) {
	row := q.db.QueryRow(ctx, upsertPlatform, arg.Name, arg.Description)
	var i Platform
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRole = `-- name: UpsertRole :one
insert into roles (name, description, rank)
values ($1, $2, $3)
on conflict (name) do update
   set description = excluded.description,
       rank        = excluded.rank
returning name, description, rank, is_system, created_at, updated_at
`

type UpsertRoleParams struct {
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
	Rank        int32  `db:"rank" json:"rank"`
}

func (q *Queries) UpsertRole(ctx context.Context, arg UpsertRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, upsertRole, arg.Name, arg.Description, arg.Rank)
	var i Role
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.Rank,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
