// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: values.sql

package database

import (
	"context"
	"encoding/json"

	uuid "github.com/google/uuid"
)

const deleteIntermediateValue = `-- name: DeleteIntermediateValue :execrows
delete from intermediate_settings where group_id = $1 and setting_id = $2
`

type DeleteIntermediateValueParams struct {
	GroupID   uuid.UUID `db:"group_id" json:"group_id"`
	SettingID uuid.UUID `db:"setting_id" json:"setting_id"`
}

func (q *Queries) DeleteIntermediateValue(ctx context.Context, arg DeleteIntermediateValueParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIntermediateValue, arg.GroupID, arg.SettingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePersonalValue = `-- name: DeletePersonalValue :execrows
delete from personal_settings where user_id = $1 and setting_id = $2
`

type DeletePersonalValueParams struct {
	UserID    string    `db:"user_id" json:"user_id"`
	SettingID uuid.UUID `db:"setting_id" json:"setting_id"`
}

func (q *Queries) DeletePersonalValue(ctx context.Context, arg DeletePersonalValueParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePersonalValue, arg.UserID, arg.SettingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteServerValue = `-- name: DeleteServerValue :execrows
delete from server_settings where setting_id = $1
`

func (q *Queries) DeleteServerValue(ctx context.Context, settingID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServerValue, settingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIntermediateValue = `-- name: GetIntermediateValue :one
select id, group_id, setting_id, value, visible, is_enforced, created_at, created_by, updated_at, updated_by from intermediate_settings where group_id = $1 and setting_id = $2
`

type GetIntermediateValueParams struct {
	GroupID   uuid.UUID `db:"group_id" json:"group_id"`
	SettingID uuid.UUID `db:"setting_id" json:"setting_id"`
}

func (q *Queries) GetIntermediateValue(ctx context.Context, arg GetIntermediateValueParams) (IntermediateSetting, error) {
	row := q.db.QueryRow(ctx, getIntermediateValue, arg.GroupID, arg.SettingID)
	var i IntermediateSetting
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SettingID,
		&i.Value,
		&i.Visible,
		&i.IsEnforced,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getPersonalValue = `-- name: GetPersonalValue :one
select id, user_id, setting_id, value, created_at, created_by, updated_at, updated_by from personal_settings where user_id = $1 and setting_id = $2
`

type GetPersonalValueParams struct {
	UserID    string    `db:"user_id" json:"user_id"`
	SettingID uuid.UUID `db:"setting_id" json:"setting_id"`
}

func (q *Queries) GetPersonalValue(ctx context.Context, arg GetPersonalValueParams) (PersonalSetting, error) {
	row := q.db.QueryRow(ctx, getPersonalValue, arg.UserID, arg.SettingID)
	var i PersonalSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SettingID,
		&i.Value,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getServerValue = `-- name: GetServerValue :one
select id, setting_id, value, created_at, created_by, updated_at, updated_by from server_settings where setting_id = $1
`

func (q *Queries) GetServerValue(ctx context.Context, settingID uuid.UUID) (ServerSetting, error) {
	row := q.db.QueryRow(ctx, getServerValue, settingID)
	var i ServerSetting
	err := row.Scan(
		&i.ID,
		&i.SettingID,
		&i.Value,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listIntermediateValuesForGroup = `-- name: ListIntermediateValuesForGroup :many
select id, group_id, setting_id, value, visible, is_enforced, created_at, created_by, updated_at, updated_by from intermediate_settings where group_id = $1
`

func (q *Queries) ListIntermediateValuesForGroup(ctx context.Context, groupID uuid.UUID) ([]IntermediateSetting, error) {
	rows, err := q.db.Query(ctx, listIntermediateValuesForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntermediateSetting{}
	for rows.Next() {
		var i IntermediateSetting
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SettingID,
			&i.Value,
			&i.Visible,
			&i.IsEnforced,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalValuesForUser = `-- name: ListPersonalValuesForUser :many
select id, user_id, setting_id, value, created_at, created_by, updated_at, updated_by from personal_settings where user_id = $1
`

func (q *Queries) ListPersonalValuesForUser(ctx context.Context, userID string) ([]PersonalSetting, error) {
	rows, err := q.db.Query(ctx, listPersonalValuesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonalSetting{}
	for rows.Next() {
		var i PersonalSetting
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SettingID,
			&i.Value,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIntermediateValue = `-- name: UpsertIntermediateValue :one
insert into intermediate_settings (group_id, setting_id, value, visible, is_enforced, created_by, updated_by)
values ($1, $2, $3, $4, $5, $6, $6)
on conflict (group_id, setting_id) do update
   set value       = excluded.value,
       visible     = excluded.visible,
       is_enforced = excluded.is_enforced,
       updated_by  = excluded.updated_by
returning id, group_id, setting_id, value, visible, is_enforced, created_at, created_by, updated_at, updated_by
`

type UpsertIntermediateValueParams struct {
	GroupID    uuid.UUID       `db:"group_id" json:"group_id"`
	SettingID  uuid.UUID       `db:"setting_id" json:"setting_id"`
	Value      json.RawMessage `db:"value" json:"value"`
	Visible    bool            `db:"visible" json:"visible"`
	IsEnforced bool            `db:"is_enforced" json:"is_enforced"`
	Actor      string          `db:"actor" json:"actor"`
}

func (q *Queries) UpsertIntermediateValue(ctx context.Context, arg UpsertIntermediateValueParams) (IntermediateSetting, error) {
	row := q.db.QueryRow(ctx, upsertIntermediateValue,
		arg.GroupID,
		arg.SettingID,
		arg.Value,
		arg.Visible,
		arg.IsEnforced,
		arg.Actor,
	)
	var i IntermediateSetting
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SettingID,
		&i.Value,
		&i.Visible,
		&i.IsEnforced,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertPersonalValue = `-- name: UpsertPersonalValue :one
insert into personal_settings (user_id, setting_id, value, created_by, updated_by)
values ($1, $2, $3, $4, $4)
on conflict (user_id, setting_id) do update
   set value = excluded.value, updated_by = excluded.updated_by
returning id, user_id, setting_id, value, created_at, created_by, updated_at, updated_by
`

type UpsertPersonalValueParams struct {
	UserID    string          `db:"user_id" json:"user_id"`
	SettingID uuid.UUID       `db:"setting_id" json:"setting_id"`
	Value     json.RawMessage `db:"value" json:"value"`
	Actor     string          `db:"actor" json:"actor"`
}

func (q *Queries) UpsertPersonalValue(ctx context.Context, arg UpsertPersonalValueParams) (PersonalSetting, error) {
	row := q.db.QueryRow(ctx, upsertPersonalValue,
		arg.UserID,
		arg.SettingID,
		arg.Value,
		arg.Actor,
	)
	var i PersonalSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SettingID,
		&i.Value,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertServerValue = `-- name: UpsertServerValue :one

insert into server_settings (setting_id, value, created_by, updated_by)
values ($1, $2, $3, $3)
on conflict (setting_id) do update
   set value = excluded.value, updated_by = excluded.updated_by
returning id, setting_id, value, created_at, created_by, updated_at, updated_by
`

type UpsertServerValueParams struct {
	SettingID uuid.UUID       `db:"setting_id" json:"setting_id"`
	Value     json.RawMessage `db:"value" json:"value"`
	Actor     string          `db:"actor" json:"actor"`
}

// Each layer gets the same three operations. Writes are upserts so that a
// caller can PUT a value without first checking whether one exists.
func (q *Queries) UpsertServerValue(ctx context.Context, arg UpsertServerValueParams) (ServerSetting, error) {
	row := q.db.QueryRow(ctx, upsertServerValue, arg.SettingID, arg.Value, arg.Actor)
	var i ServerSetting
	err := row.Scan(
		&i.ID,
		&i.SettingID,
		&i.Value,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
